/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */
package hr.fer.ppj.labos.ppj21.parse;
public interface MiniJavaConstants {

  int EOF = 0;
  int ONE_COMMENT = 5;
  int MULTI_COMMENT = 6;
  int OTHER_COMMENT = 7;
  int INTEGER_LITERAL = 8;
  int IF = 9;
  int INT = 10;
  int NEW = 11;
  int VOID = 12;
  int ELSE = 13;
  int TRUE = 14;
  int MAIN = 15;
  int THIS = 16;
  int WHILE = 17;
  int FALSE = 18;
  int CLASS = 19;
  int PUBLIC = 20;
  int STATIC = 21;
  int STRING = 22;
  int LENGTH = 23;
  int RETURN = 24;
  int BOOLEAN = 25;
  int EXTENDS = 26;
  int IDENTIFIER = 27;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ONE_COMMENT>",
    "<MULTI_COMMENT>",
    "<OTHER_COMMENT>",
    "<INTEGER_LITERAL>",
    "\"if\"",
    "\"int\"",
    "\"new\"",
    "\"void\"",
    "\"else\"",
    "\"true\"",
    "\"main\"",
    "\"this\"",
    "\"while\"",
    "\"false\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"String\"",
    "\"length\"",
    "\"return\"",
    "\"boolean\"",
    "\"extends\"",
    "<IDENTIFIER>",
    "\"{\"",
    "\"(\"",
    "\"[\"",
    "\"]\"",
    "\")\"",
    "\"}\"",
    "\";\"",
    "\",\"",
    "\"System.out.println\"",
    "\"=\"",
    "\"&&\"",
    "\"<\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"!\"",
    "\".\"",
  };

}
