//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.ast;
import hr.fer.ppj.labos.ppj21.gui.util.tree.SimpleNodeVisitor;
import hr.fer.ppj.labos.ppj21.visitor.*;
/**
 * Grammar production:
 * f0 -> MainClass()
 * f1 -> ( ClassDecl() )*
 * f2 -> <EOF>
 */
public class Program implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	public MainClass f0;
	public NodeListOptional f1;
	public NodeToken f2;

   public Program(MainClass n0, NodeListOptional n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public Program(MainClass n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
      f2 = new NodeToken("");
   }

   public void accept(Visitor v) throws Exception {
      v.visit(this);
   }
   public Object accept(ObjectVisitor v, Object argu) throws Exception {
      return v.visit(this,argu);
   }
	public Object accept(ObjectVisitor v) throws Exception {
		return v.visit(this, null);
	}
	public Object accept(SimpleNodeVisitor v) throws Exception {
		return v.visit(this);
	}

}

