//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.ast;
import hr.fer.ppj.labos.ppj21.visitor.*;
/**
 * Grammar production:
 * f0 -> Type()
 * f1 -> ID()
 * f2 -> ";"
 */
public class VarDecl implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public Type f0;
   public ID f1;
   public NodeToken f2;

   public VarDecl(Type n0, ID n1, NodeToken n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public VarDecl(Type n0, ID n1) {
      f0 = n0;
      f1 = n1;
      f2 = new NodeToken(";");
   }

   public void accept(Visitor v) throws Exception {
      v.visit(this);
   }
   public Object accept(ObjectVisitor v, Object argu) throws Exception {
      return v.visit(this,argu);
   }
	public Object accept(ObjectVisitor v) throws Exception {
		return v.visit(this, null);
	}

}