/* Generated By:JJTree: Do not edit this line. ASTGreaterThanOrEqual.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hr.fer.ppj21.labos.parser;

public
@SuppressWarnings("all")
class ASTGreaterThanOrEqual extends SimpleNode {
  public ASTGreaterThanOrEqual(int id) {
    super(id);
  }

  public ASTGreaterThanOrEqual(MiniJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a49280920d4f00349ed16a7d170409ed (do not edit this line) */
