/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hr.fer.ppj21.labos.parser;

public
@SuppressWarnings("all")
class ASTIdentifier extends SimpleNode {
	private String value;
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(MiniJava p, int id) {
    super(p, id);
  }

  public void setValue(String value) {
	  this.value=value;
  }
  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  
  public String toString() {
	  return "Identifier: " + value;
  }
}
/* JavaCC - OriginalChecksum=9ef4754efd35412fff8f6ff7cb311fb9 (do not edit this line) */
