/* Generated By:JJTree: Do not edit this line. ASTInteger.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hr.fer.ppj21.labos.parser;

public
@SuppressWarnings("all")
class ASTInteger extends SimpleNode {
	private String value;
  public ASTInteger(int id) {
    super(id);
  }

  public ASTInteger(MiniJava p, int id) {
    super(p, id);
  }

  public void setValue(String value) {
	  this.value=value;
  }
  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
  public String toString() {
	  return "Integer: " + value;
  }
}
/* JavaCC - OriginalChecksum=9abd5d1b9e55965c3da01c18ef7c2acf (do not edit this line) */
