/* Generated By:JJTree: Do not edit this line. ASTIntegerType.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hr.fer.ppj21.labos.parser;

public
@SuppressWarnings("all")
class ASTIntegerType extends SimpleNode {
  public ASTIntegerType(int id) {
    super(id);
  }

  public ASTIntegerType(MiniJava p, int id) {
    super(p, id);
  }
  

  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cf84dbe4c932dbacb0ab90b75ce0e050 (do not edit this line) */
