/* Generated By:JJTree: Do not edit this line. ASTMethodBodyBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hr.fer.ppj21.labos.parser;

public
@SuppressWarnings("all")
class ASTMethodBodyBlock extends SimpleNode {
  public ASTMethodBodyBlock(int id) {
    super(id);
  }

  public ASTMethodBodyBlock(MiniJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0a3a7be1f0cc08700c1d98fe697d43f6 (do not edit this line) */
