/* Generated By:JJTree: Do not edit this line. ASTMethodBoodyBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hr.fer.ppj21.labos.parser;

public
@SuppressWarnings("all")
class ASTMethodBoodyBlock extends SimpleNode {
  public ASTMethodBoodyBlock(int id) {
    super(id);
  }

  public ASTMethodBoodyBlock(MiniJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=7d9cb17c13c00b6419408e1c0c72bb2d (do not edit this line) */
