/* Generated By:JJTree: Do not edit this line. ASTUnaryAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package hr.fer.ppj21.labos.parser;

public
@SuppressWarnings("all")
class ASTUnaryAssignment extends SimpleNode {
  public ASTUnaryAssignment(int id) {
    super(id);
  }

  public ASTUnaryAssignment(MiniJava p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MiniJavaVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2bdb4d78a730bc6b8c5ee1560416ff1f (do not edit this line) */
