package hr.fer.ppj21.labos.lexer.util;

import JFlex.sym;

public class MySym implements sym {
	public static final String EOF    = "End of file";
    public static final String ERROR  = "Error";
    public static final String SEMICOLON = "Semicolon";
    public static final String KONST = "Constant";
    public static final String ZNAK = "Character";
    public static final String STRING = "String";
    public static final String IDENTIFIKATOR = "Identifier";
    public static final String KEYWORD = "Keyword";
    public static final String OPERATOR = "Operator";
    public static final String OBRACKET = "Open brace";
    public static final String CBRACKET = "Closed brace";
    public static final String SPECIAL = "Special char";
    
    public static final String IF = "IF";
    public static final String THEN = "THEN";
    public static final String ELSE = "ELSE";
    public static final String ELSEIF = "ELSEIF";
    public static final String BEGIN = "BEGIN";
    public static final String END = "END";
    public static final String WHILE = "WHILE";
    public static final String DO = "DO";
    public static final String FOR = "FOR";
    public static final String RETURN = "RETURN";
    public static final String NULL = "NULL";
    public static final String INT = "INT";
    public static final String CHAR = "CHAR";
    public static final String BOOL = "BOOL";
    public static final String VOID = "VOID";
    public static final String CLASS = "CLASS";
    public static final String EXTENDS = "EXTENDS";
    public static final String THIS = "THIS";
    public static final String SEMICOL = "SEMICOL";
    public static final String ASSIGN = "ASSIGN";
    public static final String OR = "OR";
    public static final String AND = "AND";
    public static final String NOT = "NOT";
    public static final String LT = "LT";
    public static final String GT = "GT";
    public static final String LE = "LE";
    public static final String GE = "GE";
    public static final String EQ = "EQ";
    public static final String NE = "NE";
    public static final String PLUS = "PLUS";
    public static final String MINUS = "MINUS";
    public static final String TIMES = "TIMES";
    public static final String DIV = "DIV";
    public static final String MOD = "MOD";
    public static final String INC = "INC";
    public static final String DEC = "DEC";
    public static final String AMP = "AMP";
    public static final String PTR = "PTR";
    public static final String LR = "LR";
    public static final String RR = "RR";
    public static final String LS = "LS";
    public static final String RS = "RS";
    public static final String LC = "LC";
    public static final String RC = "RC";
    public static final String DOT = "DOT";
    public static final String COMMA = "COMMA";
    public static final String ETC = "ETC";
    public static final String VARERROR = "VARERROR";
    public static final String UNEXPECTED = "UNEXPECTED";
}
