//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.syntaxtree;
import hr.fer.ppj.labos.ppj21.gui.util.tree.SimpleNodeVisitor;
import hr.fer.ppj.labos.ppj21.visitor.*;
/**
 * Grammar production:
 * f0 -> ( "!" )*
 * f1 -> ( <NEW> <INT> "[" Exp() "]" | <NEW> ID() "(" ")" | Atom() )
 * f2 -> ( MethodCall() )*
 */
public class Factor implements Node {
	static final long serialVersionUID = 0;
   public NodeListOptional f0;
   public NodeChoice f1;
   public NodeListOptional f2;

   public Factor(NodeListOptional n0, NodeChoice n1, NodeListOptional n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public void accept(Visitor v) throws Exception {
      v.visit(this);
   }
   public Object accept(ObjectVisitor v, Object argu) throws Exception {
      return v.visit(this,argu);
   }
   public Object accept(SimpleNodeVisitor v) throws Exception {
		return v.visit(this);
	}

	public Object accept(ObjectVisitor v) throws Exception {
		return v.visit(this, null);
	}
}

