//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.syntaxtree;
import hr.fer.ppj.labos.ppj21.gui.util.tree.SimpleNodeVisitor;
import hr.fer.ppj.labos.ppj21.visitor.*;
/**
 * Grammar production:
 * f0 -> Term()
 * f1 -> ( ( "+" | "-" ) Term() )*
 */
public class MathExp implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public Term f0;
   public NodeListOptional f1;

   public MathExp(Term n0, NodeListOptional n1) {
      f0 = n0;
      f1 = n1;
   }

   public void accept(Visitor v) throws Exception {
      v.visit(this);
   }
   public Object accept(SimpleNodeVisitor v) throws Exception {
		return v.visit(this);
	}

   public Object accept(ObjectVisitor v, Object argu) throws Exception {
      return v.visit(this,argu);
   }
	public Object accept(ObjectVisitor v) throws Exception {
		return v.visit(this, null);
	}
}