//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.syntaxtree;
import hr.fer.ppj.labos.ppj21.visitor.*;
/**
 * Grammar production:
 * f0 -> "." <LENGTH>
 *       | "." ID() "(" ( Exp() ( "," Exp() )* )? ")"
 *       | "[" Exp() "]"
 */
public class MethodCall implements Node {
	static final long serialVersionUID = 0;
   public NodeChoice f0;

   public MethodCall(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(Visitor v) throws Exception {
      v.visit(this);
   }
   public Object accept(ObjectVisitor v, Object argu) throws Exception {
      return v.visit(this,argu);
   }
	public Object accept(ObjectVisitor v) throws Exception {
		return v.visit(this, null);
	}
}

