//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.syntaxtree;
import hr.fer.ppj.labos.ppj21.gui.util.tree.SimpleNodeVisitor;
import hr.fer.ppj.labos.ppj21.visitor.*;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
	
   public void accept(Visitor v) throws Exception;
   public Object accept(ObjectVisitor v, Object argu) throws Exception;
   public Object accept(SimpleNodeVisitor v) throws Exception;

}

