//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.syntaxtree;
import hr.fer.ppj.labos.ppj21.visitor.*;

import java.util.ArrayList;

/**
 * Represents a grammar choice, e.g. ( A | B )
 */
public class NodeChoice implements Node {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	public NodeChoice(Node node) {
		this(node, -1);
	}

	public NodeChoice(Node node, int whichChoice) {
		choice = node;
		which = whichChoice;
	}

	public void accept(Visitor v) throws Exception {
		choice.accept(v);
	}

	public Object accept(ObjectVisitor v, Object argu) throws Exception {
		return choice.accept(v, argu);
	}

	public Node choice;

	public int which;

	public ArrayList<Node> toList() {
		ArrayList<Node> result = new ArrayList<Node>();
		result.add(choice);
		return result;
	}
}
