//
// Generated by JTB 1.2.2
//

package hr.fer.ppj.labos.ppj21.syntaxtree;
import hr.fer.ppj.labos.ppj21.visitor.*;
/**
 * Grammar production:
 * f0 -> "{" ( Statement() )* "}"
 *       | <IF> "(" Exp() ")" Statement() <ELSE> Statement()
 *       | <WHILE> "(" Exp() ")" Statement()
 *       | "System.out.println" "(" Exp() ")" ";"
 *       | ID() "=" Exp() ";"
 *       | ID() "[" Exp() "]" "=" Exp() ";"
 */
public class Statement implements Node {
   /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
public NodeChoice f0;

   public Statement(NodeChoice n0) {
      f0 = n0;
   }

   public void accept(Visitor v) throws Exception {
      v.visit(this);
   }
   public Object accept(ObjectVisitor v, Object argu) throws Exception {
      return v.visit(this,argu);
   }
	public Object accept(ObjectVisitor v) throws Exception {
		return v.visit(this, null);
	}
}

